### ISSUE TITLE
Include input file into repo and load it from project root dir

### ISSUE THREAD

**Issue by wj-0816** [razmannazli/assessmentTC#2]
Previous input file has missing record of `2000,100,M,Harry`. Please commit input file into repo and load it from project root dir. 

Refer to below for correct input

> Record ID,Parent ID,Gender,Name
10000,1005,M,Louis
1000,100,M,William
502,30,M,Mokhzani
10000,1005,M,Charlotte
105,3,F,Diana
100,10,M,Charles
300,10,M,Andrew
300,20,M,Andrew
10,1,F,Elizabeth II
400,10,M,Edward
30,5,M,Mahathir
503,30,F,Marina
10000,1005,M,George
100,20,M,Charles
10000,1000,M,Louis
400,20,M,Edward
1005,3,F,Catherine
501,30,M,Mukhriz
10000,1000,M,George
10000,1000,M,Charlotte
200,20,F,Anne
1000,105,M,William
1000,100,M,William
20,2,M,Philip
200,10,F,Anne
2000,105,M,Harry
2000,100,M,Harry

https://github.com/razmannazli/assessmentTC/blob/fb4f2233c7f0593e8d79aa1ae89e546d57729d52/src/com/razman/Main.java#L21

**Comment by razmannazli** [comment]
Added file to repo.
