### ISSUE TITLE
Skip duplicate

### ISSUE THREAD

**Issue by wj-0816** [razmannazli/assessmentTC#4]
In exercise 2, `Elizabeth II, Philip` family tree is occurred twice and `Diana, Charles` is part of `Elizabeth II, Philip` family.  
Modify your algorithm to print optimized family tree, each family should only occur once. 

Expected result : 
> Mahathir
    Mokhzani
    Marina
    Mukhriz
Philip, Elizabeth II  // or Elizabeth II, Philip
    Charles, Diana
        William, Catherine
            Louis
            George
            Charlotte
        Harry
    Andrew
    Edward

![image](https://user-images.githubusercontent.com/83930943/210459487-e6cb1455-6400-409e-9eb5-2efb18bdc550.png)

https://github.com/razmannazli/assessmentTC/blob/fb4f2233c7f0593e8d79aa1ae89e546d57729d52/src/com/razman/Main.java#L146-L163

**Comment by razmannazli** [comment]
Added checking if existed will not printing.
