### ISSUE TITLE
Add validation to handle unexpected input file

### ISSUE THREAD

**Issue by wj-0816** [razmannazli/assessmentTC#5]
Input file could be stored as wrong format. Add in validation to cater scenario such as each line doesn't have 4 elements or key for map is missing

Possible input: 
> Record ID,Parent ID,Gender,Name
10000,1005,M,Louis
1000,100,M,William
502,30,Mokhzani
10000,1005,M,Charlotte
105,3,F,Diana
100,10,M,Charles
300,10,M,Andrew
,20,M,Andrew
10,1,F,Elizabeth II
400,10,M,Edward
30,5,M,Mahathir
503,,F,Marina
10000,1005,M,George
100,20,M,Charles
10000,1000,M,Louis
400,20,M,Edward
1005,3,F,Catherine
501,30,M,Mukhriz
10000,1000,M,George
10000,1000,M,Charlotte
200,,F,Anne
1000,105,M,William
1000,100,M,William
20,2,M,Philip
200,10,F,Anne
2000,105,M,Harry
2000,100,M,Harry

https://github.com/razmannazli/assessmentTC/blob/fb4f2233c7f0593e8d79aa1ae89e546d57729d52/src/com/razman/Main.java#L28

https://github.com/razmannazli/assessmentTC/blob/fb4f2233c7f0593e8d79aa1ae89e546d57729d52/src/com/razman/Main.java#L66

https://github.com/razmannazli/assessmentTC/blob/fb4f2233c7f0593e8d79aa1ae89e546d57729d52/src/com/razman/Main.java#L100

**Comment by razmannazli** [comment]
Added validation that the value must have all 4 fields only proceed to create object.
